# Generated by Django 2.0.5 on 2018-06-16 18:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_subdivision_werker'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Werker',
            new_name='Worker',
        ),
    ]
